/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardValidateRouteImport } from './routes/dashboard/validate'
import { Route as DashboardUserManagementRouteImport } from './routes/dashboard/user-management'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRoleManagementRouteImport } from './routes/dashboard/role-management'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard/attendance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidateRoute = DashboardValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserManagementRoute = DashboardUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoleManagementRoute = DashboardRoleManagementRouteImport.update({
  id: '/role-management',
  path: '/role-management',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/role-management': typeof DashboardRoleManagementRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/user-management': typeof DashboardUserManagementRoute
  '/dashboard/validate': typeof DashboardValidateRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/login': typeof LoginRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/role-management': typeof DashboardRoleManagementRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/user-management': typeof DashboardUserManagementRoute
  '/dashboard/validate': typeof DashboardValidateRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/role-management': typeof DashboardRoleManagementRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/user-management': typeof DashboardUserManagementRoute
  '/dashboard/validate': typeof DashboardValidateRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/dashboard'
    | '/login'
    | '/dashboard/attendance'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/role-management'
    | '/dashboard/settings'
    | '/dashboard/user-management'
    | '/dashboard/validate'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/dashboard/attendance'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/role-management'
    | '/dashboard/settings'
    | '/dashboard/user-management'
    | '/dashboard/validate'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/dashboard'
    | '/login'
    | '/dashboard/attendance'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/role-management'
    | '/dashboard/settings'
    | '/dashboard/user-management'
    | '/dashboard/validate'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validate': {
      id: '/dashboard/validate'
      path: '/validate'
      fullPath: '/dashboard/validate'
      preLoaderRoute: typeof DashboardValidateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management': {
      id: '/dashboard/user-management'
      path: '/user-management'
      fullPath: '/dashboard/user-management'
      preLoaderRoute: typeof DashboardUserManagementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/role-management': {
      id: '/dashboard/role-management'
      path: '/role-management'
      fullPath: '/dashboard/role-management'
      preLoaderRoute: typeof DashboardRoleManagementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRoleManagementRoute: typeof DashboardRoleManagementRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUserManagementRoute: typeof DashboardUserManagementRoute
  DashboardValidateRoute: typeof DashboardValidateRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRoleManagementRoute: DashboardRoleManagementRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUserManagementRoute: DashboardUserManagementRoute,
  DashboardValidateRoute: DashboardValidateRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
